export default {
    login: 'not.loading.yet!',
    id: 42133389,
    node_id: 'MDQ6VXNlcjQyMTMzMzg5',
    avatar_url: 'https://avatars2.githubusercontent.com/u/6049160?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/goleedev',
    html_url: 'https://github.com/goleedev',
    followers_url: 'https://api.github.com/users/goleedev/followers',
    following_url:
      'https://api.github.com/users/goleedev/following{/other_user}',
    gists_url: 'https://api.github.com/users/goleedev/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/goleedev/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/goleedev/subscriptions',
    organizations_url: 'https://api.github.com/users/goleedev/orgs',
    repos_url: 'https://api.github.com/users/goleedev/repos',
    events_url: 'https://api.github.com/users/goleedev/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/goleedev/received_events',
    type: 'User',
    site_admin: false,
    name: null,
    company: null,
    blog: null,
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 0,
    followers: 3,
    following: 0,
    created_at: '2018-08-06T06:48:23Z',
    updated_at: '2020-07-08T05:01:32Z',
  };